### PR TITLE
WiP: Attach the last request fetch()'s response to the finish event

### PR DESCRIPTION
**Pull request by SakiiR**

### CODE REVIEW

**Comment by SakiiR** [comment]
I need this :)

**Comment by Buzut** [comment]
Hi SakiiR,
I know I'm late to the battle, but may I know why you might (and others) need this?

**Comment by SakiiR** [comment]
Hi @Buzut !

I needed this cause my API returns some information at the end of the last HTTP request (link to the uploaded file for exemple)

**Comment by Buzut** [comment]
Sounds like it can be useful indeed. I'm definitely willing to merge your improvements.
Can you just format your update with spaces around braces so that it passes linter validation. Like so:

```js
this._eventTarget.dispatchEvent(new CustomEvent('finish', { body }));
```

Also, would you update the README to reflect this new feature?

**Comment by SakiiR** [comment]
hi ! 

Is this enough ? (:

**Comment by Buzut** [comment]
Looks good to me this time!

**Pull request merged**
